version: '2'
services:
  <%= name %>:
    command: /bin/sh -c "npm i && npm run start"
    image: node:6.4
    working_dir: /opt
    volumes:
     - .:/opt
    environment:
      TERM: dumb
    networks:
      - service

networks:
  service: