version: '2'
services:
  <%= name %>:
    command: /bin/sh -c "npm i && npm run make && npm run startDev"
    image: node:8
    working_dir: /opt
    volumes:
      - .:/opt
    environment:
      TERM: dumb
    networks:
      - service

networks:
  service:
